name: GraalVM Native Image builds
on: [push, pull_request]
jobs:
  build:
    name: Demo on Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build natively
        run: ./gradlew quarkusBuild "-Dquarkus.package.type=native"
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.os }}
          path: ./build/quarkus-app/quarkus-run.jar
