name: GraalVM Native Image builds for Quarkus
on: [push, pull_request]
jobs:
  build:
    name: Demo on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x64
          - os: ubuntu-latest
            arch: ARM64
          - os: ubuntu-latest
            arch: ARMv7
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: ARM64
          - os: windows-latest
            arch: x64
    steps:
      - uses: actions/checkout@v4
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - name: Setup MSVC for Windows
        if: matrix.os == 'windows-latest'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build natively on Windows
        if: matrix.os == 'windows-latest'
        run: ./gradlew quarkusBuild "-Dquarkus.package.type=native" -Parch=${{ matrix.arch }}
      - name: Build natively on Unix
        if: matrix.os != 'windows-latest'
        run: ./gradlew quarkusBuild -Dquarkus.package.type=native -Parch=${{ matrix.arch }}
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: demo-${{ matrix.os }}-${{ matrix.arch }}
          path: |
            build/quarkus-java-demo-1.0-SNAPSHOT-runner*
            build/quarkus-artifact.properties
